# This Dockerfile can be used to run unit tests.
# This image is published on the Docker Hub: kanboard/tests:latest
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y -q && \
    apt-get install -y \
        apache2 \
        libapache2-mod-php \
        php-cli \
        php-mbstring \
        php-sqlite3 \
        php-opcache \
        php-json \
        php-ldap \
        php-gd \
        php-zip \
        php-curl \
        php-xml \
        php-mysql \
        php-pgsql \
        php-pear \
        php-dev \
        composer \
        npm \
        git \
        make \
        mariadb-client \
        postgresql-client

# Apache rewrite
RUN a2enmod rewrite

# Set php.ini path in config-set
RUN pear config-set php_ini /etc/php/7.4/cli/php.ini

# Install xdebug
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/lib/php/20190902/ -name xdebug.so)" > /etc/php/7.4/cli/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /etc/php/7.4/cli/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=on" >> /etc/php/7.4/cli/conf.d/xdebug.ini \
    && rm -rf /tmp/pear