version: '3'
services:
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        command: mysqld --lower_case_table_names=1
        command: mysqld --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
        ports: 
        - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: kanboard
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
        - mysql-volume:/var/lib/mysql
    kanboard:
        image: felipefelizardo/kanboard:dev
        ports:
        - "80:80"
        volumes:
        - ./:/var/www/html
        environment:
            DATABASE_URL: mysql://root:root@mysql/kanboard
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
        - "8080:80"
        links: 
        - mysql
        environment:
        - PMA_ARBITRARY=1
volumes:
  mysql-volume: