name: Unit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  Sqlite:
    runs-on: ubuntu-latest
    container: kanboard/tests:latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Unit tests with Sqlite
      run: ./vendor/bin/phpunit -c tests/units.sqlite.xml

  Mysql:
    runs-on: ubuntu-latest
    container: kanboard/tests:latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: kanboard_unit_test
        ports:
        - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Integration tests with Mysql
      run: ./vendor/bin/phpunit -c tests/units.mysql.xml
      env:
        DB_HOSTNAME: mysql
        DB_PORT: ${{ job.services.mysql.ports[3306] }}    
